<?php
$countryArray = array('Afghanistan', 'Afrique du sud', 'Albanie', 'Algérie', 'Allemagne', 'Andorre', 'Angleterre', 'Angola', 'Anguilla', 'Antarctique', 'Antigua et Barbuda', 'Antilles néerlandaises', 'Arabie saoudite', 'Argentine', 'Arménie', 'Aruba', 'Australie', 'Autriche', 'Azerbaïdjan', 'Bahamas',
                                'Bahrain', 'Bangladesh', 'Belgique', 'Belize', 'Benin', 'Bermudes', 'Bhoutan', 'Biélorussie', 'Bolivie', 'Bosnie-Herzégovine', 'Botswana', 'Bouvet', 'Brésil', 'Brunei', 'Bulgarie', 'Burkina Faso', 'Burundi', 'Cambodge', 'Cameroun', 'Canada', 'Cap Vert', 'Cayman', 'Chili', 'Chine', 'Christmas', 'Chypre', 'Cocos',
                                'Colombie', 'Comores', 'Congo', 'Cook', 'Corée du Nord', 'Corée du Sud', 'Costa Rica', 'Côte d\'Ivoire', 'Croatie', 'Cuba', 'Danemark', 'Djibouti', 'Dominique', 'Egypte', 'El Salvador', 'Emirats arabes unis', 'Equateur', 'Erythrée', 'Espagne', 'Estonie', 'Etats-Unis', 'Ethiopie', 'Falkland', 'Féroé', 'Fidji',
                                'Finlande', 'France', 'Gabon', 'Gambie', 'Géorgie', 'Ghana', 'Gibraltar', 'Grèce', 'Grenade', 'Groenland', 'Guadeloupe', 'Guam', 'Guatemala', 'Guinée', 'Guinée Equatoriale', 'Guinée-Bissau', 'Guyane', 'Guyane française', 'Haïti', 'Honduras', 'Hongrie', 'Inde', 'Indonésie', 'Irak', 'Iran', 'Irlande', 'Islande', 'Israël', 'Italie', 'Jamaïque', 'Japon',
                                'Jordanie', 'Kazakhstan', 'Kenya', 'Kirghizistan', 'Kiribati', 'Koweit', 'La Barbad', 'Laos', 'Lesotho', 'Lettonie', 'Liban', 'Libéria', 'Libye', 'Liechtenstein', 'Lithuanie', 'Luxembourg', 'Macau', 'Macédoine',
                                'Madagascar', 'Malaisie', 'Malawi', 'Maldives', 'Mali', 'Malte', 'Mariannes du Nord', 'Maroc', 'Marshall', 'Martinique', 'Maurice', 'Mauritanie', 'Mayotte', 'Mexique', 'Micronésie',
                                'Moldavie', 'Monaco', 'Mongolie', 'Montserrat', 'Mozambique', 'Myanmar', 'Namibie', 'Nauru', 'Nepal', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'Norfolk', 'Norvège', 'Nouvelle Calédonie', 'Nouvelle-Zélande', 'Oman', 'Ouganda', 'Ouzbékistan', 'Pakistan', 'Palau', 'Panama', 'Papouasie-Nouvelle-Guinée', 'Paraguay', 'Pays-Bas', 'Pérou', 'Philippines', 'Pitcairn', 'Pologne', 'Polynésie française', 'Porto Rico', 'Portugal', 'Qatar', 'République centrafricaine', 'République Dominicaine', 'République tchèque', 'Réunion', 'Roumanie', 'Royaume-Uni', 'Russie', 'Rwanda', 'Sahara Occidental', 'Saint Pierre et Miquelon', 'Saint Vincent et les Grenadine', 'Saint-Kitts et Nevis', 'Saint-Marin', 'Sainte Hélène', 'Sainte Lucie', 'Samoa', 'Sénégal', 'Seychelles', 'Sierra Leone',
                                'Singapour', 'Slovaquie', 'Slovénie', 'Somalie', 'Soudan', 'Sri Lanka', 'Suède', 'Suisse', 'Suriname', 'Syrie', 'Tadjikistan', 'Taiwan', 'Tanzanie', 'Tchad', 'Thailande', 'Timor', 'Togo', 'Tokelau', 'Tonga', 'Trinité et Tobago', 'Tunisie', 'Turkménistan', 'Turquie', 'Tuvalu', 'Ukraine', 'Uruguay', 'Vanuatu', 'Vatican', 'Venezuela', 'Vierges', 'Vietnam', 'Wallis et Futuna', 'Yemen', 'Yougoslavie', 'Zaïre', 'Zambie', 'Zimbabwe');
                           
$nationalityArray = array('Afghane', 'Albanaise', 'Algerienne', 'Allemande', 'Americaine', 'Andorrane', 'Angolaise', 'Antiguaise et barbudienne', 'Argentine', 'Armenienne', 'Australienne',
                    'Autrichienne', 'Azerbaïdjanaise', 'Bahamienne', 'Bahreinienne', 'Bangladaise', 'Barbadienne', 'Belge', 'Belizienne', 'Beninoise', 'Bhoutanaise', 'Bielorusse', 'Birmane',
                    'Bissau-Guinéenne', 'Bolivienne', 'Bosnienne', 'Botswanaise', 'Bresilienne', 'Britannique', 'Bruneienne', 'Bulgare', 'Burkinabe', 'Camerounaise', 'Canadienne', 'Cap-verdienne',
                    'Centrafricaine', 'Chilienne', 'Chinoise', 'Chypriote', 'Colombienne', 'Comorienne', 'Congolaise', 'Costaricaine', 'Croate', 'Cubaine', 'Danoise', 'Djiboutienne', 'Dominicaine',
                    'Dominiquaise', 'Egyptienne', 'Emirienne', 'Equato-guineenne', 'Equatorienne', 'Erythreenne', 'Espagnole', 'Est-timoraise', 'Estonienne', 'Ethiopienne', 'Fidjienne',
                    'Finlandaise', 'Française', 'Gabonaise', 'Grenadienne', 'Guatemalteque', 'Guineenne', 'Guyanienne', 'Haïtienne', 'Hellenique', 'Hongroise', 'Indienne', 'Indonesienne',
                    'Irakienne', 'Irlandaise', 'Islandaise', 'Israélienne', 'Italienne', 'Ivoirienne', 'Jamaïcaine', 'Japonaise', 'Jordanienne', 'Kazakhstanaise', 'Kenyane', 'Kirghize', 'Kiribatienne',
                    'Kittitienne-et-nevicienne', 'Kossovienne', 'Koweitienne', 'Laotienne', 'Lesothane', 'Lettone', 'Libanaise', 'Liberienne', 'Libyenne', 'Liechtensteinoise', 'Lituanienne',
                    'Luxembourgeoise', 'Macedonienne', 'Malaisienne', 'Malawienne', 'Maldivienne', 'Malgache', 'Malienne', 'Maltaise', 'Marocaine', 'Marshallaise', 'Mauricienne', 'Mauritanienne',
                    'Mexicaine', 'Micronesienne', 'Moldave', 'Monegasque', 'Mongole', 'Montenegrine', 'Mozambicaine', 'Namibienne', 'Nauruane', 'Neerlandaise', 'Neo-zelandaise',
                    'Nepalaise', 'Nicaraguayenne', 'Nigeriane', 'Nigerienne', 'Nord-coréenne', 'Norvegienne', 'Omanaise', 'Ougandaise', 'Ouzbeke', 'Pakistanaise', 'Palau', 'Palestinienne',
                    'Panameenne', 'Papouane-neoguineenne', 'Paraguayenne', 'Peruvienne', 'Philippine', 'Polonaise', 'Portoricaine', 'Portugaise', 'Qatarienne', 'Roumaine', 'Russe',
                    'Rwandaise', 'Saint-lucienne', 'Saint-marinaise', 'Saint-vincentaise-et-grenadine', 'Salomonaise', 'Salvadorienne', 'Samoane', 'Santomeenne', 'Saoudienne', 'Senegalaise',
                    'Serbe', 'Seychelloise', 'Sierra-leonaise', 'Singapourienne', 'Slovaque', 'Slovene', 'Somalienne', 'Soudanaise', 'Sri-lankaise', 'Sud-africaine', 'Sud-coréenne', 'Suedoise',
                    'Suisse', 'Surinamaise', 'Swazie', 'Syrienne', 'Tadjike', 'Taiwanaise', 'Tanzanienne', 'Tchadienne', 'Tcheque', 'Thaïlandaise', 'Togolaise', 'Tonguienne', 'Trinidadienne',
                    'Tunisienne', 'Turkmene', 'Turque', 'Tuvaluane', 'Ukrainienne', 'Uruguayenne', 'Vanuatuane', 'Venezuelienne', 'Vietnamienne', 'Yemenite', 'Zambienne', 'Zimbabweenne');
                
$regions = array('Alsace' , 'Aquitaine' , 'Auvergne' , 'Basse-Normandie' , 'Bourgogne' , 'Bretagne' , 'Centre' , 'Champagne-Ardenne' , 'Corse' , 'Franche-Comté' , 'Haute-Normandie' ,
                              'Île-de-France' , 'Languedoc-Roussillon' , 'Limousin' , 'Lorraine' , 'Midi-Pyrénées' , 'Nord-Pas-de-Calais' , 'Pays de la Loire' , 'Picardie' , 'Poitou-Charentes' , 'Provence-Alpes-Côte d\'Azur' ,
                             'Rhône-Alpes' , 'Guadeloupe' , 'Guyane' , 'La Réunion' , 'Martinique' , 'Mayotte');
